\documentclass[11pt,preprint, authoryear]{elsarticle}

\usepackage{lmodern}
%%%% My spacing
\usepackage{setspace}
\setstretch{1.2}
\DeclareMathSizes{12}{14}{10}{10}

% Wrap around which gives all figures included the [H] command, or places it "here". This can be tedious to code in Rmarkdown.
\usepackage{float}
\let\origfigure\figure
\let\endorigfigure\endfigure
\renewenvironment{figure}[1][2] {
    \expandafter\origfigure\expandafter[H]
} {
    \endorigfigure
}

\let\origtable\table
\let\endorigtable\endtable
\renewenvironment{table}[1][2] {
    \expandafter\origtable\expandafter[H]
} {
    \endorigtable
}


\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi

\usepackage{amssymb, amsmath, amsthm, amsfonts}

\def\bibsection{\section*{References}} %%% Make "References" appear before bibliography


\usepackage[round]{natbib}

\usepackage{longtable}
\usepackage[margin=2.3cm,bottom=2cm,top=2.5cm, includefoot]{geometry}
\usepackage{fancyhdr}
\usepackage[bottom, hang, flushmargin]{footmisc}
\usepackage{graphicx}
\numberwithin{equation}{section}
\numberwithin{figure}{section}
\numberwithin{table}{section}
\setlength{\parindent}{0cm}
\setlength{\parskip}{1.3ex plus 0.5ex minus 0.3ex}
\usepackage{textcomp}
\renewcommand{\headrulewidth}{0.2pt}
\renewcommand{\footrulewidth}{0.3pt}

\usepackage{array}
\newcolumntype{x}[1]{>{\centering\arraybackslash\hspace{0pt}}p{#1}}

%%%%  Remove the "preprint submitted to" part. Don't worry about this either, it just looks better without it:
\makeatletter
\def\ps@pprintTitle{%
  \let\@oddhead\@empty
  \let\@evenhead\@empty
  \let\@oddfoot\@empty
  \let\@evenfoot\@oddfoot
}
\makeatother

 \def\tightlist{} % This allows for subbullets!

\usepackage{hyperref}
\hypersetup{breaklinks=true,
            bookmarks=true,
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=blue,
            pdfborder={0 0 0}}


% The following packages allow huxtable to work:
\usepackage{siunitx}
\usepackage{multirow}
\usepackage{hhline}
\usepackage{calc}
\usepackage{tabularx}
\usepackage{booktabs}
\usepackage{caption}


\newenvironment{columns}[1][]{}{}

\newenvironment{column}[1]{\begin{minipage}{#1}\ignorespaces}{%
\end{minipage}
\ifhmode\unskip\fi
\aftergroup\useignorespacesandallpars}

\def\useignorespacesandallpars#1\ignorespaces\fi{%
#1\fi\ignorespacesandallpars}

\makeatletter
\def\ignorespacesandallpars{%
  \@ifnextchar\par
    {\expandafter\ignorespacesandallpars\@gobble}%
    {}%
}
\makeatother

\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newenvironment{CSLReferences}%
  {\setlength{\parindent}{0pt}%
  \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces}%
  {\par}


\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{5}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}

%%% Include extra packages specified by user

%%% Hard setting column skips for reports - this ensures greater consistency and control over the length settings in the document.
%% page layout
%% paragraphs
\setlength{\baselineskip}{12pt plus 0pt minus 0pt}
\setlength{\parskip}{12pt plus 0pt minus 0pt}
\setlength{\parindent}{0pt plus 0pt minus 0pt}
%% floats
\setlength{\floatsep}{12pt plus 0 pt minus 0pt}
\setlength{\textfloatsep}{20pt plus 0pt minus 0pt}
\setlength{\intextsep}{14pt plus 0pt minus 0pt}
\setlength{\dbltextfloatsep}{20pt plus 0pt minus 0pt}
\setlength{\dblfloatsep}{14pt plus 0pt minus 0pt}
%% maths
\setlength{\abovedisplayskip}{12pt plus 0pt minus 0pt}
\setlength{\belowdisplayskip}{12pt plus 0pt minus 0pt}
%% lists
\setlength{\topsep}{10pt plus 0pt minus 0pt}
\setlength{\partopsep}{3pt plus 0pt minus 0pt}
\setlength{\itemsep}{5pt plus 0pt minus 0pt}
\setlength{\labelsep}{8mm plus 0mm minus 0mm}
\setlength{\parsep}{\the\parskip}
\setlength{\listparindent}{\the\parindent}
%% verbatim
\setlength{\fboxsep}{5pt plus 0pt minus 0pt}



\begin{document}



\begin{frontmatter}  %

\title{Data Science exam: Question 4 (Netflix)}

% Set to FALSE if wanting to remove title (for submission)




\author[Add1]{Erik Valentin Schulte}
\ead{26802325@sun.ac.su}





\address[Add1]{Stellenbosch University, South Africa}

\cortext[cor]{Corresponding author: Erik Valentin Schulte}

\begin{abstract}
\small{
\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{23}
\tightlist
\item
\end{enumerate}
}
\end{abstract}

\vspace{1cm}





\vspace{0.5cm}

\end{frontmatter}



%________________________
% Header and Footers
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\pagestyle{fancy}
\chead{}
\rhead{}
\lfoot{}
\rfoot{\footnotesize Page \thepage}
\lhead{}
%\rfoot{\footnotesize Page \thepage } % "e.g. Page 2"
\cfoot{}

%\setlength\headheight{30pt}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%________________________

\headsep 35pt % So that header does not go over title




\hypertarget{introduction}{%
\section{\texorpdfstring{Introduction
\label{Introduction}}{Introduction }}\label{introduction}}

Both datasets have a common identifier by which it can be knitted. I
merge the two dataset and perform the following analysis. First, I
present a table with some summary statistic about the newly merged
dataset.

\begin{verbatim}
## 
## =============================================================
## Statistic         N       Mean     St. Dev.    Min     Max   
## -------------------------------------------------------------
## release_year    77,213 2,014.921     8.133    1,953   2,022  
## runtime         77,213   96.494     35.540      0      251   
## seasons         13,976   2.074       2.269      1      42    
## imdb_score      72,937   6.466       1.106    1.500   9.500  
## imdb_votes      72,850 58,719.810 155,392.800   5   2,268,288
## tmdb_popularity 77,202   27.792     67.366    0.600 1,823.374
## tmdb_score      76,093   6.685       1.026    1.000  10.000  
## -------------------------------------------------------------
\end{verbatim}

Using the stargazer function we can see that the earliest movie was
released in 1953 and the latest movies in 2022, while the medians of
movies releases is 2018. The maximum runtime is 251 minutes and the mean
run time for each movie is 96 minutes.

The range of the seasons of the netflix data is 1 to 42.

IMDB scores range from 1.5 to 9.5, the average rating of all the movies
contained in the dataset is 6.466.

For the tmb score, there the rating scale ranges from 1 to 10 and the
average rating is slighly higher with 6.685.

\hypertarget{what-are-good-movies}{%
\section{What are good movies?}\label{what-are-good-movies}}

First, I looks at specific directors that did well, specifically those
who got ratings from the Internet Movie Database and the TMDB score of
higher than 8.4. 8.4 was choosen arbitrarily to have just the right
amount of observations in the graph.

\begin{figure}[H]

{\centering \includegraphics{Q4_files/figure-latex/unnamed-chunk-3-1} 

}

\caption{Good movies.\label{Figure1}}\label{fig:unnamed-chunk-3}
\end{figure}

We can see from graph 1 that there are a few directors that did really
well. There is also a lot of variation in the runtime from very short
shows with less than 30 minutes by the Director He Xiaofeng or rather
long shows by Shin Won-ho which take more than 150 minutes. More of the
good ratings are allocated towards shows rather than movies. I would
recommend my superiors into looking into the works of the Directors I
found.

\hypertarget{what-are-bad-movies}{%
\section{What are bad movies?}\label{what-are-bad-movies}}

The data are also rich in what my superiors should not do. They should
be careful with works that were produced by single countries only.
There, seems to be especially bad movies and shows coming from India and
the US, since the cumulative runtime exceeds 25000 hourse for India and
15.000hours for the US.. However, these are most likely also two very
high producing countries. It is also apparent from the bad movie data
that most bad movies do not have an age certificaiton. Most are
available for India (PG-13) and the US (R) and Japan (TV-PG).

\begin{figure}[H]

{\centering \includegraphics{Q4_files/figure-latex/unnamed-chunk-5-1} 

}

\caption{Bad movies.\label{Figure2}}\label{fig:unnamed-chunk-5}
\end{figure}

Looking at the graph with the bad movies with low ratings we can see
where they were produced. Interestingly, the worst movies were produced
by single countries and not by co-production.

\bibliography{Tex/ref}





\end{document}
